[build]
  command = "pip install -r requirements.txt && streamlit run app.py"
  publish = "."
  base = "/"

[build.environment]
  PYTHON_VERSION = "3.8"  # Adjust Python version as needed
  RUSTUP_HOME = "/opt/buildhome/.rustup"
  CARGO_HOME = "/opt/buildhome/.cargo"
  PATH = "/opt/buildhome/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

[[plugins]]
  package = "@netlify/plugin-rustup"
