[build]
  command = "pip install -r requirements.txt && streamlit run app.py"
  publish = "."
  base = "/"

[build.environment]
  PYTHON_VERSION = "3.12"  # Use a Python version supported by Netlify and your project
