[build]
  command = "pip install -r requirements.txt && streamlit run app.py"
  publish = "."
  base = "/"

[build.environment]
  PYTHON_VERSION = "3.8" # Specify the Python version required

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
