[build]
  command = "pip install -r requirements.txt && streamlit run app.py --server.port=$PORT --server.enableCORS=false"
  publish = "."
  base = "/"

[build.environment]
  PYTHON_VERSION = "3.12"  # Adjust Python version as needed
